# Regresión lineal


In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

### Crear datos para crear el modelo

In [2]:
entrada = np.array([[0.54],[1.14],[2.08],[3.5],[8.64],[9.38],[10]])
salida = np.array([ [2.06],[2.68],[2.66],[3.6],[5.26],[6.04],[6]])
nuevas_instancias = np.array([[5.92],[7]])

### Crear el modelo, entrenarlo y visualizar los parámetros

In [3]:
reg = LinearRegression().fit(entrada, salida)

print(reg.coef_)
print(reg.intercept_)

[[0.40557178]]
[1.99877536]


### Predecir el valor de nuevas instancias

In [4]:
reg.predict(nuevas_instancias)

array([[4.39976031],
       [4.83777783]])



---


# Regresión lineal con regularización L2



In [5]:
from sklearn.linear_model import Ridge

In [6]:
regL2 = Ridge(alpha=1).fit(entrada, salida)

print(regL2.coef_)
print(regL2.intercept_)

[[0.40167169]]
[2.01843181]


In [7]:
regL2.predict(nuevas_instancias)

array([[4.39632823],
       [4.83013366]])

---

# Regresión lineal con regularización L1

In [8]:
from sklearn.linear_model import Lasso

In [9]:
regL1 = Lasso(alpha=1).fit(entrada, salida)

print(regL1.coef_)
print(regL1.intercept_)

[0.33760428]
[2.34133156]


In [10]:
regL1.predict(nuevas_instancias)

array([4.33994891, 4.70456153])